### ISSUE TITLE
Greek Pluperfect Middle-Passive Indicative mp table

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#179]
we do not show any matches or highlighted cells in the following tables:
m.-p.: velar plosive stem 
m.-p.: stem in λ 
m.-p.: stem in ν 
the exact match for these tables is shown in m.-p.: vowel stem, m.-p.: dental plosive stem, m.-p.: labial plosive stem 
also, the table is missing from the greek verb browser
e.g. ἐπεφάσμεθα  it does not have the match in m.-p.: stem in ν  but in the other m.-p tables m.-p.: vowel stem, m.-p.: dental plosive stem, m.-p.: labial plosive stem

**Comment by balmas** [comment]
I believe this one is fixed by the change for #220

**Comment by balmas** [comment]
ready for testing in https://github.com/alpheios-project/webextension/tree/v2.0.3.2/dist

**Comment by monzug** [comment]
1) we are still missing the tables from the verb browser:
m.-p.: velar plosive stem
m.-p.: stem in λ
m.-p.: stem in ν
these tables should show in the Pluperfect Middle-Passive Indicative table
2) also the matching is not working for these tables.
 e.g.   ἐπέπραξο   2nd person singular m.-p.: velar plosive stem. 
the highlighted cells are in the  m.-p.: vowel stem, m.-p.: dental plosive stem, m.-p.: labial plosive stem
3)  ἐλελύκετε   shows 2 tables:  Pluperfect Middle-Passive Indicative active and the  οἶδα: Perfect System with no matching. I do not think it should show the second one.
<mood>indicative</mood>
<num>plural</num>
<pers>2nd</pers>
<tense>pluperfect</tense>
<voice>active</voice>
<stemtype>perf_act</stemtype>
<derivtype>reg_conj</derivtype>

**Comment by balmas** [comment]
When testing this, please retest matching for οἶδα: Perfect System with this fix, because I changed the rules for it to avoid it coming up for ἐλελύκετε

**Comment by balmas** [comment]
Please test in https://github.com/alpheios-project/webextension/tree/v2.0.3.3/dist

**Comment by balmas** [comment]
I'm not sure if we are getting too many matches in the table now, but also don't know if we have all of the data needed to distinguish between the different stems here to make sure we only get the right one.

**Comment by monzug** [comment]
ᾔδετον  and  ᾐδέτην   and  ᾔδετε  go to  ω-Verbs: Present System Active and not to οἶδα: perfect system but it works the same in the release.
for ᾖσαν we show three tables instead of two (and one is different) and they look ok.
this is fixed from my side. Bridget?

**Comment by balmas** [comment]
ok, great. We can't do anything about ᾔδετον and ᾐδέτην and ᾔδετε  right now because Morpheus reports them as w_stem verbs only
